package com.endcy.ai.guardrail;

/**
 * Output guardrail interface.
 *
 * <p>Step 1.8 skeleton, Step 3.x integrated with {@link com.endcy.ai.agent.executor.DefaultAgentExecutor}.</p>
 *
 * <p>Implementations should include (enabled by configuration):
 * <ul>
 *   <li>{@code ContentModerator} — content moderation API / keyword blacklist</li>
 *   <li>{@code SchemaValidator} — validate against expected schema</li>
 *   <li>{@code ToxicFilter} — profanity/hate speech filtering</li>
 *   <li>{@code LeakageDetector} — system prompt / internal table structure leakage detection</li>
 * </ul>
 *
 * @author endcy
 * @since 2026-08-07
 */
public interface OutputGuardrail {

    /**
     * Check LLM output.
     *
     * @param llmOutput raw text generated by LLM
     * @return check result (PASS / BLOCK / REDACT)
     */
    GuardrailResult check(String llmOutput);
}
